/* App.svelte generated by Svelte v3.48.0 */
import { create_ssr_component, escape } from 'svelte/internal'
import PlaceholderClient from './placeholder.svelte'

const PlaceholderServer = create_ssr_component(
  ($$result, $$props, $$bindings, slots) => {
    return `${escape($$props.content)}`
  }
)

export default typeof document === 'undefined'
  ? PlaceholderServer
  : PlaceholderClient
