packages:
  - examples/**/*
  - packages/*

overrides:
  '@types/react': 19.2.16
  '@tanstack/angular-table-devtools': 'workspace:*'
  '@tanstack/angular-table': 'workspace:*'
  '@tanstack/lit-table': 'workspace:*'
  '@tanstack/match-sorter-utils': 'workspace:*'
  '@tanstack/preact-table-devtools': 'workspace:*'
  '@tanstack/preact-table': 'workspace:*'
  '@tanstack/react-table-devtools': 'workspace:*'
  '@tanstack/react-table': 'workspace:*'
  '@tanstack/solid-table-devtools': 'workspace:*'
  '@tanstack/solid-table': 'workspace:*'
  '@tanstack/svelte-table': 'workspace:*'
  '@tanstack/table-core': 'workspace:*'
  '@tanstack/table-devtools': 'workspace:*'
  '@tanstack/vue-table-devtools': 'workspace:*'
  '@tanstack/vue-table': 'workspace:*'

packageExtensions:
  '@analogjs/vite-plugin-angular':
    peerDependencies:
      '@angular/compiler': '^17.0.0 || ^18.0.0 || ^19.0.0 || ^20.0.0 || ^21.0.0 || ^22.0.0'
    peerDependenciesMeta:
      '@angular/compiler':
        optional: true

allowBuilds:
  # root dependency
  nx: true
  unrs-resolver: false # not directly required for build
  esbuild: true

  # @angular/build
  '@parcel/watcher': false # optional dep of @angular/build
  lmdb: false # optional dep of @angular/build
  msgpackr-extract: false # optional dep of @angular/build

  # @tanstack/vue-store
  vue-demi: false # only required for vue 2 support

cleanupUnusedCatalogs: true
minimumReleaseAge: 1440

linkWorkspacePackages: true
preferWorkspacePackages: true
blockExoticSubdeps: true
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2 || 6.3.1
