packages:
  - 'packages/*'
  - 'examples/angular/*'
  - 'examples/lit/*'
  - 'examples/preact/*'
  - 'examples/react/*'
  - 'examples/solid/*'
  - 'examples/svelte/*'
  - 'examples/vanilla/*'
  - 'examples/vue/*'
