/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherRouteRouteImport } from './routes/anotherRoute'
import { Route as IndexRouteImport } from './routes/index'

const AnotherRouteRoute = AnotherRouteRouteImport.update({
  id: '/anotherRoute',
  path: '/anotherRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherRoute': typeof AnotherRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherRoute': typeof AnotherRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherRoute': typeof AnotherRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anotherRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anotherRoute'
  id: '__root__' | '/' | '/anotherRoute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherRouteRoute: typeof AnotherRouteRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/anotherRoute': {
      id: '/anotherRoute'
      path: '/anotherRoute'
      fullPath: '/anotherRoute'
      preLoaderRoute: typeof AnotherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherRouteRoute: AnotherRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
