/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnotherRouteImport } from './routes/anotherRoute'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AnotherRouteRoute = AnotherRouteImport.update({
  path: '/anotherRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/anotherRoute': {
      id: '/anotherRoute'
      path: '/anotherRoute'
      fullPath: '/anotherRoute'
      preLoaderRoute: typeof AnotherRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AnotherRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/anotherRoute"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/anotherRoute": {
      "filePath": "anotherRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
